[theme]
base = "light"
primaryColor = "#1e6b47"
backgroundColor = "#f2f4f1"
secondaryBackgroundColor = "#e5e9e4"
textColor = "#13233a"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
enableStaticServing = true
